CONFIG_ZMK_KEYBOARD_NAME="cult"

# RGB
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_LED_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# BLE + USB
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000
